spring.main.banner-mode=off

# Datasource
# spring.datasource.initialization-mode=embedded
# spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE 
# spring.datasource.driverClassName=org.h2.Driver 
# spring.datasource.username=sa 
# spring.datasource.password=

it.tndigit.database.multidatasource = true

# Datasources - "ags"
# fascicolo.datasource
primary.datasource.initialization-mode = embedded
# primary.datasource.url = jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
primary.datasource.url = jdbc:h2:file:./target/test-classes/tempDB 
# primary.datasource.driverClassName = org.h2.jdbcx.JdbcDataSource
primary.datasource.username = sa 
primary.datasource.password =

# Datasources - "a4g"
# istruttoria.datasource
secondary.datasource.initialization-mode = embedded
# secondary.datasource.url = jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
secondary.datasource.url = jdbc:h2:file:./target/test-classes/tempDB 
# secondary.datasource.driverClassName = org.h2.jdbcx.JdbcDataSource
secondary.datasource.username = sa 
secondary.datasource.password =

# Configurazione spring e h2
spring.jpa.hibernate.ddl-auto = none
spring.h2.console.enabled = true

spring.jackson.time-zone=Europe/Rome
spring.jackson.locale=it-IT

it.tndigit.security.utente.url = http://localhost:8080/a4gutente/api/v1/

spring.mail.host=relay.infotn.it
spring.mail.port=25
a4g.mail.to=a4g@infotn.it
a4g.mail.oggetto=Errore sincronizzazione esiti antimafia CUAA,ID_DOMANDA,TIPO_DOMANDA: {0}, {1}, {2}
a4g.mail.messaggio=Il sistema ha generato la seguente eccezione: {0}